USE [towers];

CREATE TABLE request (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT DEFAULT NULL,
    CreatedBy UNIQUEIDENTIFIER DEFAULT NULL,
    LastModifiedBy UNIQUEIDENTIFIER DEFAULT NULL,
    CreatedOn DATETIME DEFAULT GETDATE(),
    LastModifiedOn DATETIME DEFAULT GETDATE()
);