USE [towers];

CREATE TABLE requeststatus (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Value VARCHAR(255) NOT NULL,
    CreatedBy UNIQUEIDENTIFIER DEFAULT NULL,
    LastModifiedBy UNIQUEIDENTIFIER DEFAULT NULL,
    CreatedOn DATETIME DEFAULT GETDATE(),
    LastModifiedOn DATETIME DEFAULT GETDATE()
);