USE [towers];

CREATE TABLE usersetting (
    UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Theme UNIQUEIDENTIFIER DEFAULT NULL,
    AccentColor VARCHAR(7) DEFAULT NULL,
    CreatedBy UNIQUEIDENTIFIER DEFAULT NULL,
    LastModifiedBy UNIQUEIDENTIFIER DEFAULT NULL,
    CreatedOn DATETIME DEFAULT GETDATE(),
    LastModifiedOn DATETIME DEFAULT GETDATE()
);