CREATE TABLE user (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Email VARCHAR(320) UNIQUE NOT NULL,
    PhoneNumber VARCHAR(25) DEFAULT NULL
);